### PR TITLE
General update

### PR DESCRIPTION
**Pull request by balessan**
Fixes # Adding docker-compose, adding tests, adding integration of DBS_Arweave and DBS_Filecoin

### CODE REVIEW

**Comment by balessan** [comment]
Need to add some repository secrets for the tests to pass.

**Comment by jamiehewitt15** [comment]
There are quite a lot of changes here, can you share some more details about what issues they fix?

**Comment by jamiehewitt15** [comment]
Hi @balessan,

I tried running this but it's just giving me an HTML error page when I call the `http://localhost:8000` endpoint. Is it working for you? I'm wondering if there is something wrong with my setup? 

image

**Comment by balessan** [comment]
Hi @jamiehewitt15 

It looks like the migrations are not run so the DB is not initialized. Is the build of the container ok ?
Can confirm it works on my side, I tried from scratch on yesterday while we were discussing.

Happy to take some time if screenshare is needed to understand.

**Review by jamiehewitt15 — APPROVED** [review]
Thanks for this update, I've managed to get it up and running. Let's merge this and then iterate further from the main branch with any alterations we need

**Pull request merged**
