### PR TITLE
DBS - Setup of the project

### LINKED ISSUE #8: Storages list endpoint
**Description:**  Information about supported storage types & payments

**Path:**  /storages/

Arguments:  None

Returns:
```json
[
    {
        "type": "filecoin",
        "description":  "File storage on FileCoin",
        "payment":
            [ 
                {
                    "chainId": 1,
                    "acceptedTokens": 
                        [ 
                            "OCEAN": "0xOCEAN_on_MAINNET",
                            "DAI": "0xDAI_ON_MAINNET"
                        ]
                },
                {
                    "chainId": "polygon_chain_id",
                    "acceptedTokens": 
                        [ 
                            "OCEAN": "0xOCEAN_on_POLYGON",
                            "DAI": "0xDAI_ON_POLYGON"
                        ]
                }
            ]
    },
    {
        "type": "arweave",
        "description":  "File storage on Arweave",
        "payment":
            [ 
                {
                    "chainId": 1,
                    "acceptedTokens": 
                        [ 
                            "OCEAN": "0xOCEAN_on_MAINNET",
                            "DAI": "0xDAI_ON_MAINNET"
                        ]
                },
                {
                    "chainId": "arweave_chain_id",
                    "acceptedTokens": 
                        [ 
                            "ARWEAVE": "0xARWEAVEtoken_on_arweaveChain"
                        ]
                }
            ]
    }
]    
```

### PR DESCRIPTION
**Pull request by balessan**
Fixes #8 

Changes proposed in this PR:

- First implementation of the models needed to store every information in database
- First endpoint implementation with the info, returning JSON formatted Data as follows:

```
[
  {
    "type": "filecoin",
    "description": "The file coin storage description.",
    "payment_methods": [
      {
        "chain_id": "1",
        "accepted_tokens": [
          {
            "OCEAN": "0xOCEAN_on_MAINNET"
          },
          {
            "DAI": "0xDAI_ON_MAINNET"
          }
        ]
      },
      {
        "chain_id": "polygon_chain_id",
        "accepted_tokens": [
          {
            "OCEAN": "0xOCEAN_on_POLYGON"
          },
          {
            "DAI": "0xDAI_ON_POLYGON"
          }
        ]
      }
    ]
  }
]
```

@happy-dev @alexcos20 : I am unsure about `payment_methods`. In the spec it is called `payment` but while processing it I was pretty sure it was actually the list of available payment methods for a given storage solution. Is that right ?

And about the list of accepted tokens, I do not really get why there is a multiplicity of accepted tokens by payment methods ?

So implementation of the first API public endpoint, but the easiest one. WIll now proceed with the POST on `quotes` and GET on `quote`.

Regards.

### CODE REVIEW

**Comment by alexcos20** [comment]
please do not merge it, with failing tests ..

is this all so far ?

**Comment by balessan** [comment]
@alexcos20 : Yes, that's just the setup step, I am working locally on the actual implementation, will push actual API endpoint by tomorrow night.

What's missing and what I would like to get information is target infrastructure for test deployment. Do you have any available target infrastructure ? Like heroku or something ?

**Comment by alexcos20** [comment]
no, this will be backed as docker and we will run it in our infrastructure

**Comment by balessan** [comment]
Ok, perfect, thanks for the answer.

**Pull request merged**
